from datetime import datetime

from pydantic import BaseModel, Field, field_validator


class PropertyBase(BaseModel):
    """Base property model with common fields."""

    first_line_address: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="First line of the property's address",
    )
    second_line_address: str | None = Field(
        None, max_length=255, description="Second line of the property's address"
    )
    city_or_town: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="City or town of the property's address",
    )
    description: str | None = Field(
        None,
        max_length=1000,
        description="Optional descriptive text about the property",
    )

    @classmethod
    @field_validator("first_line_address", "city_or_town")
    def validate_required_strings(cls, v):
        """Ensure required string fields are not empty after stripping whitespace."""
        if v is not None:
            v = v.strip()
            if not v:
                raise ValueError("Field cannot be empty")
        return v

    @classmethod
    @field_validator("second_line_address", "description")
    def validate_optional_strings(cls, v):
        """Strip whitespace from optional string fields."""
        if v is not None:
            v = v.strip()
            if not v:  # If empty after stripping, set to None
                return None
        return v


class PropertyCreate(PropertyBase):
    """Schema for creating a new property (excludes auto-generated fields)."""

    pass


class PropertyUpdate(BaseModel):
    first_line_address: str | None = Field(
        None,
        min_length=1,
        max_length=255,
        description="First line of the property's address",
    )
    second_line_address: str | None = Field(
        None, max_length=255, description="Second line of the property's address"
    )
    city_or_town: str | None = Field(
        None,
        min_length=1,
        max_length=100,
        description="City or town of the property's address",
    )
    description: str | None = Field(
        None,
        max_length=1000,
        description="Optional descriptive text about the property",
    )

    @classmethod
    @field_validator("first_line_address", "city_or_town")
    def validate_non_empty_required_strings(cls, v: str) -> str:
        """Ensure required string fields are not empty after stripping whitespace."""
        if v is not None:
            v = v.strip()
            if not v:
                raise ValueError("Field cannot be empty")
        return v

    @classmethod
    @field_validator("second_line_address", "description")
    def validate_non_empty_optional_strings(cls, v: str) -> str | None:
        """Strip whitespace from optional string fields."""
        if v is not None:
            v = v.strip()
            if not v:  # If empty after stripping, set to None
                return None
        return v


class Property(PropertyBase):
    id: str = Field(
        ...,
        description="Unique identifier for the property (auto-generated by Firestore)",
    )
    date_created: datetime = Field(
        ..., description="Date and time when the property record was created"
    )
    date_last_updated: datetime = Field(
        ..., description="Date and time when the property record was last updated"
    )

    class Config:
        json_encoders = {datetime: lambda dt: dt.isoformat()}
        json_schema_extra = {
            "example": {
                "id": "guid",
                "first_line_address": "123 Main Street",
                "second_line_address": "Apartment 4B",
                "city_or_town": "London",
                "description": "Modern 2-bedroom apartment with garden access",
                "date_created": "2024-01-15T10:30:00Z",
                "date_last_updated": "2024-01-20T14:45:00Z",
            }
        }
