from datetime import datetime

from pydantic import BaseModel, Field, field_validator


class TransactionCategoryBase(BaseModel):
    """Base transaction category model with common fields."""
    name: str = Field(..., min_length=1, max_length=100, description="Name of the transaction category")
    description: str | None = Field(None, max_length=500, description="Optional descriptive text about the category")

    @classmethod
    @field_validator("name")
    def validate_required_strings(cls, v):
        """Ensure required string fields are not empty after stripping whitespace."""
        if v is not None:
            v = v.strip()
            if not v:
                raise ValueError("Field cannot be empty")
        return v

    @classmethod
    @field_validator("description")
    def validate_optional_strings(cls, v):
        """Strip whitespace from optional string fields."""
        if v is not None:
            v = v.strip()
            if not v:  # If empty after stripping, set to None
                return None
        return v


class TransactionCategoryCreate(TransactionCategoryBase):
    """Schema for creating a new transaction category (excludes auto-generated fields)."""
    pass


class TransactionCategoryUpdate(BaseModel):
    """Schema for updating an existing transaction category."""
    name: str | None = Field(None, min_length=1, max_length=100, description="Name of the transaction category")
    description: str | None = Field(None, max_length=500, description="Optional descriptive text about the category")

    @classmethod
    @field_validator("name")
    def validate_non_empty_required_strings(cls, v: str) -> str:
        """Ensure required string fields are not empty after stripping whitespace."""
        if v is not None:
            v = v.strip()
            if not v:
                raise ValueError("Field cannot be empty")
        return v

    @classmethod
    @field_validator("description")
    def validate_non_empty_optional_strings(cls, v: str) -> str | None:
        """Strip whitespace from optional string fields."""
        if v is not None:
            v = v.strip()
            if not v:  # If empty after stripping, set to None
                return None
        return v


class TransactionCategory(TransactionCategoryBase):
    """Complete transaction category model including auto-generated fields."""
    id: str = Field(..., description="Unique identifier for the category (auto-generated by Firestore)")
    date_created: datetime = Field(..., description="Date and time when the category record was created")
    date_last_updated: datetime = Field(..., description="Date and time when the category record was last updated")

    class Config:
        json_encoders = {
            datetime: lambda dt: dt.isoformat()
        }
        json_schema_extra = {
            "example": {
                "id": "category-guid",
                "name": "Rent Income",
                "description": "Monthly rental income from properties",
                "date_created": "2024-01-15T10:30:00Z",
                "date_last_updated": "2024-01-20T14:45:00Z"
            }
        }