from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, field_validator


class TransactionType(str, Enum):
    """Enumeration for transaction types."""
    INCOME = "income"
    EXPENSE = "expense"


class TransactionBase(BaseModel):
    """Base transaction model with common fields."""
    transaction_type: TransactionType = Field(..., description="Type of transaction: 'income' or 'expense'")
    transaction_category_id: str = Field(..., min_length=1, description="ID of the associated transaction category")
    amount: float = Field(..., gt=0, description="Amount of the transaction (must be positive)")
    description: str | None = Field(None, max_length=1000, description="Optional description of the transaction")
    transaction_date: datetime = Field(..., description="Date and time when the transaction took place")
    property_id: str | None = Field(None, min_length=1, description="Optional ID of the associated property")

    @classmethod
    @field_validator("transaction_category_id")
    def validate_transaction_category_id(cls, v):
        """Ensure transaction category ID is not empty after stripping whitespace."""
        if v is not None:
            v = v.strip()
            if not v:
                raise ValueError("Transaction category ID cannot be empty")
        return v

    @classmethod
    @field_validator("property_id")
    def validate_property_id(cls, v):
        """Strip whitespace from property ID and set to None if empty."""
        if v is not None:
            v = v.strip()
            if not v:
                return None
        return v

    @classmethod
    @field_validator("description")
    def validate_description(cls, v):
        """Strip whitespace from optional description field."""
        if v is not None:
            v = v.strip()
            if not v:  # If empty after stripping, set to None
                return None
        return v


class TransactionCreate(TransactionBase):
    """Schema for creating a new transaction (excludes auto-generated fields)."""
    pass


class TransactionUpdate(BaseModel):
    """Schema for updating an existing transaction."""
    transaction_type: TransactionType | None = Field(None, description="Type of transaction: 'income' or 'expense'")
    transaction_category_id: str | None = Field(None, min_length=1, description="ID of the associated transaction category")
    amount: float | None = Field(None, gt=0, description="Amount of the transaction (must be positive)")
    description: str | None = Field(None, max_length=1000, description="Optional description of the transaction")
    transaction_date: datetime | None = Field(None, description="Date and time when the transaction took place")
    property_id: str | None = Field(None, min_length=1, description="Optional ID of the associated property")

    @classmethod
    @field_validator("transaction_category_id")
    def validate_transaction_category_id(cls, v):
        """Ensure transaction category ID is not empty after stripping whitespace."""
        if v is not None:
            v = v.strip()
            if not v:
                raise ValueError("Transaction category ID cannot be empty")
        return v

    @classmethod
    @field_validator("property_id")
    def validate_property_id(cls, v):
        """Strip whitespace from property ID and set to None if empty."""
        if v is not None:
            v = v.strip()
            if not v:
                return None
        return v

    @classmethod
    @field_validator("description")
    def validate_description(cls, v):
        """Strip whitespace from optional description field."""
        if v is not None:
            v = v.strip()
            if not v:  # If empty after stripping, set to None
                return None
        return v


class Transaction(TransactionBase):
    """Complete transaction model including auto-generated fields."""
    id: str = Field(..., description="Unique identifier for the transaction (auto-generated by Firestore)")
    date_created: datetime = Field(..., description="Date and time when the transaction record was created")

    class Config:
        json_encoders = {
            datetime: lambda dt: dt.isoformat()
        }
        json_schema_extra = {
            "example": {
                "id": "transaction-guid",
                "transaction_type": "income",
                "transaction_category_id": "category-guid",
                "amount": 1200.00,
                "description": "Monthly rent payment from tenant",
                "transaction_date": "2024-01-15T09:00:00Z",
                "property_id": "property-guid",
                "date_created": "2024-01-15T10:30:00Z"
            }
        }